server:
   port: ${API_GATEWAY_PORT:6666}
eureka:
   instance:
      ip-address: ${API_GATEWAY_SERVICE_IP:loalhost}
      prefer-ip-address: true
   client:
      serviceUrl:
         defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
spring:
   application:
      name: api-gateway-service
   cloud:
      gateway:
         routes:
         -  id: authentication-api
            uri: lb://authentication-service  # 目标URL，lb代表从注册中心获取服务，lb是Load Balance的缩写
            predicates:  # 匹配路径转发
            - Path=/spring/cloud/example/auth/v1/**
            filters: # Filter集合
            - StripPrefix=5 # 从第几级开始转发